title: yeKblog
description: Mes trucs en vrac
show_downloads: false
google_analytics:
theme: jekyll-theme-midnight

social:
  twitter: y3K_c1m
  github:  yeKcim
  mastodon:
   - username: yekcim
     instance: framapiaf.org

lang: fr-FR
date_format: "%d/%m/%Y"

show_excerpts: true
excerpt_separator: <!--more-->
